# Docker-Compose project definition for SoftiCAR GitHub Runner.
#
# Invoked by softicar-github-runner.sh
#
# -------- Mandatory Environment Variables --------
#
# RUNNER_ENV_FILE
#   The absolute path to the "softicar-github-runner.env" file on the host.
#   Mandatory; via environment variable
#   Default: (undefined)
#
# -------- Optional Environment Variables --------
#
# RUNNER_VERSION_OVERRIDE
#   Enforces the "runner" service/image to be built with the specified version of GitHub Actions Runner.
#   If undefined, the latest available version will be used.
#   Optional; via softicar-github-runner.env
#   Default: (undefined)
#
# NEXUS_CHECK_INTERVAL
#   The polling interval for the "nexus" service health check.
#   Optional; via softicar-github-runner.env
#   Default: "5s"
#
# NEXUS_CHECK_RETRIES
#   The number of retries for the "nexus" service health check.
#   Optional; via softicar-github-runner.env
#   Default: "20"
#
# NEXUS_CHECK_START_PERIOD
#   The time to wait until the first "nexus" service health check.
#   Optional; via softicar-github-runner.env
#   Default: "80s"
#
# NEXUS_CHECK_TIMEOUT
#   The amount of time after which an individual "nexus" service health check is considered failed.
#   Should be smaller than NEXUS_CHECK_INTERVAL.
#   Optional; via softicar-github-runner.env
#   Default: "4s"
#
# NEXUS_VERSION
#   The version of the "sonatype/nexus3" image.
#   Optional; via softicar-github-runner.env
#   Default: "3.34.1"

version: "3.4"
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:${NEXUS_VERSION:-3.34.1}
    ports:
      - "8081:8081"
    volumes:
      - "nexus-data:/nexus-data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8081/"]
      start_period: ${NEXUS_CHECK_START_PERIOD:-80s}
      interval: ${NEXUS_CHECK_INTERVAL:-5s}
      retries: ${NEXUS_CHECK_RETRIES:-20}
      timeout: ${NEXUS_CHECK_TIMEOUT:-4s}

  runner:
    container_name: runner
    image: softicar/softicar-github-runner
    build:
      context: ./runner
      # Arguments required at image build time.
      args:
        - RUNNER_VERSION_OVERRIDE=${RUNNER_VERSION_OVERRIDE}
    env_file:
      # Arguments required at container run time.
      - ${RUNNER_ENV_FILE}
    depends_on:
      nexus:
        condition: service_healthy
    runtime: sysbox-runc
    links:
      - nexus

volumes:
  # A non-prefixed volume that is created if necessary.
  nexus-data:
    name: nexus-data
