# Environment variables:
# - NEXUS_DATA_VOLUME_NAME
#     TODO describe
# - NEXUS_PROXY_PORT
#     TODO describe
# - NEXUS_HEALTH_INTERVAL
#     TODO describe
# - NEXUS_HEALTH_RETRIES
#     TODO describe
# - NEXUS_HEALTH_START_PERIOD
#     TODO describe
# - NEXUS_HEALTH_TIMEOUT
#     TODO describe
# - NEXUS_VERSION
#     TODO describe
# - RUNNER_BUILD_PROPERTIES_FILE
#     TODO describe

version: "3.4"
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:${NEXUS_VERSION:-3.34.1}
    ports:
      - ${NEXUS_PROXY_PORT:-8081}
    volumes:
      - "${NEXUS_DATA_VOLUME_NAME:-nexus-data}:/nexus-data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${NEXUS_PROXY_PORT:-8081}/"]
      start_period: ${NEXUS_HEALTH_START_PERIOD:-90s}
      interval: ${NEXUS_HEALTH_INTERVAL:-10s}
      retries: ${NEXUS_HEALTH_RETRIES:-9}
      timeout: ${NEXUS_HEALTH_TIMEOUT:-5s}

  runner:
    container_name: runner
    build:
      context: .                # modify, after stuff was moved to sub-folder
      dockerfile: Dockerfile    # TODO try to omit
#     args:                     # TODO add if necessary
    image: softicar/softicar-github-runner
    depends_on:
      nexus:
        condition: service_healthy
    runtime: sysbox-runc
#   restart: always
    volumes:
      - "${RUNNER_BUILD_PROPERTIES_FILE:-/home/softicar/.softicar/build.properties}:/home/softicar/.softicar/build.properties:read-only"
    links:
      - nexus
