# Docker-Compose project definition for SoftiCAR GitHub Runner.
#
# Invoked by softicar-github-runner-service.sh
#
# The following environment variables may optionally be defined via "softicar-github-runner-service.env":
#
# NEXUS_CHECK_INTERVAL
#   The polling interval for the "nexus" service health check.
#
# NEXUS_CHECK_RETRIES
#   The number of retries for the "nexus" service health check.
#
# NEXUS_CHECK_START_PERIOD
#   The time to wait until the first "nexus" service health check.
#
# NEXUS_CHECK_TIMEOUT
#   The amount of time after which an individual "nexus" service health check is considered failed.
#   Must be smaller than NEXUS_CHECK_INTERVAL.
#
# NEXUS_VERSION
#   The version of the "sonatype/nexus3" image.
#
# RUNNER_ADOPT_OPEN_JDK_VERSION
#   The "Eclipse Adoptium OpenJDK" version to use in the runner.
#
# RUNNER_DOCKER_COMPOSE_VERSION
#   The "Docker Compose" version to use in the runner.
#
# RUNNER_DOCKER_DAEMON_CONFIG
#   The content of the "daemon.json" file for the Docker engine in the runner.
#
# RUNNER_DUMB_INIT_VERSION
#   The "Dumb-Init" version to use in the runner.
#
# RUNNER_RELEASE_DOWNLOAD_URL
#   The URL of the GitHub Actions Runner .tar.gz archive with which the runner image is built (see https://github.com/actions/runner/releases).
#   Can be used to downgrade to an older GitHub Actions Runner release.
#   If undefined, the latest available release will be used.
#   Undefined by default. Should remain undefined unless absolutely necessary.

version: "3.4"
services:
  nexus:
    container_name: nexus
    image: softicar/nexus
    build:
      context: ../nexus-image
      args:
        - NEXUS_VERSION=${NEXUS_VERSION:-3.34.1}
    ports:
      - "8081:8081"
      - "8123:8123"
    volumes:
      - "nexus-data:/nexus-data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8081/"]
      start_period: ${NEXUS_CHECK_START_PERIOD:-80s}
      interval: ${NEXUS_CHECK_INTERVAL:-5s}
      retries: ${NEXUS_CHECK_RETRIES:-20}
      timeout: ${NEXUS_CHECK_TIMEOUT:-4s}

  runner:
    container_name: runner
    image: softicar/softicar-github-runner
    build:
      context: ../runner-image
      args:
        - RUNNER_ADOPT_OPEN_JDK_VERSION=${RUNNER_ADOPT_OPEN_JDK_VERSION:-21.0.2+13}
        - RUNNER_DOCKER_COMPOSE_VERSION=${RUNNER_DOCKER_COMPOSE_VERSION:-1.29.2}
        - RUNNER_DUMB_INIT_VERSION=${RUNNER_DUMB_INIT_VERSION:-1.2.5}
        - RUNNER_RELEASE_DOWNLOAD_URL=${RUNNER_RELEASE_DOWNLOAD_URL}
    environment:
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - GITHUB_RUNNER_LABELS=${GITHUB_RUNNER_LABELS}
      - GITHUB_RUNNER_NAME=${GITHUB_RUNNER_NAME}
      - GITHUB_RUNNER_TOKEN=${GITHUB_RUNNER_TOKEN}
    depends_on:
      nexus:
        condition: service_healthy
    runtime: sysbox-runc
    links:
      - nexus

volumes:
  # A non-prefixed volume that is created if necessary.
  nexus-data:
    name: nexus-data
